name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node version compatible with your project
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the Docusaurus site
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }} # Automatically provided by GitHub
          publish_dir: ./build # Directory containing the built site
          cname: manurukavina.com # Your custom domain